/*
 * DeEmbed
 * Copyright (C) Frans Schreuder 2016 <info@schreuderelectronics.com>
 *
software is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * software is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef DEEMBED_H
#define DEEMBED_H

#include <QMainWindow>
#include "cal-dialog.h"
#include "cal-spar.h"
#include "calstdsdialog.h"
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private slots:
    ///! Opens a dialog to set TouchStone files for SOLTI calibration
    void on_actionCalibration_files_triggered();

    ///! Clears the chart
    void on_actionClear_triggered();

    ///! Opens a touchstone file and inserts the data to the chart, the data is not yet displayed
    void on_actionOpen_Touchstone_File_triggered();

    ///! Saves any s-parameter matrix from the chart as TouchStone file
    void on_actionExport_De_embedded_Data_triggered();

    ///! Exits the application
    void on_actionExit_triggered();

    ///! Opens the calibration standards dialog
    void on_actionCalibration_standards_triggered();

    ///! Opens a webbrowser with the GitHub wiki page
    void on_actionHelp_triggered();

    ///! Opens a simple about dialog
    void on_actionAbout_DeEmbed_triggered();

    ///! Open a recent file from the QSettings recent list.
    void openRecent();

public slots:
    ///! Called from the CalStd dialog when cal stds have changed, need to recalibrate.
    void OnCalStdChanged();

    ///! Trigger to update the strings in the menu
    void OnChartDataChanged();

private:
    ///! Form Designer GUI
    Ui::MainWindow *ui;

    ///! Menu items
    QList<QAction*> recentFileActionList;
    QMenu* recentFilesMenu;
    QMenu* saveSparsMenu;

    ///! Used by the recent files
    QString currentFilePath;
    const int maxFileNr;

    ///! Object for the calibration data.
    cal_t m_cal;

    ///! Function call for recent action list
    void updateRecentActionList();

    ///! Opens a touchStone file
    void loadFile(const QString& path);
    ///! For recent action list.
    void adjustForCurrentFile(const QString& filePath);

    ///! Object for Calibration (files) dialog
    CalDialog* calDialog;

    ///! Object for Calibration Std dialog
    CalStdsDialog* calStdsDialog;

    ///! Calibration Standard values, generated by calStdsDialog on Window Creation
    tCalStd m_calStd;

    ///! CalSpar can execute Solti calibrations using the Cal function.
    CalSpar m_calibrator;

};

#endif // DEEMBED_H
