Document: deembed
Title: Debian deembed Manual
Author: <insert document author here>
Abstract: This manual describes what deembed is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deembed/deembed.sgml.gz

Format: postscript
Files: /usr/share/doc/deembed/deembed.ps.gz

Format: text
Files: /usr/share/doc/deembed/deembed.text.gz

Format: HTML
Index: /usr/share/doc/deembed/html/index.html
Files: /usr/share/doc/deembed/html/*.html
